/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-09 01:33:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class category_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Inqiure/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883781715L));
    _jspx_dependants.put("jar:file:/D:/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Inqiure/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title> 카테고리 정보 </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2> [카테고리 정보] </h2>\r\n");
      out.write("\t<input type=\"button\" id=\"btnadd\" value=\"입력칸 추가\">\r\n");
      out.write("\t<input type=\"button\" id=\"btndel\" value=\"입력칸 삭제\">\r\n");
      out.write("<form id=\"frm\" method=\"post\" action=\"categoryinsert\">\r\n");
      out.write("\t<table id=\"tbl\" border=1>\r\n");
      out.write("\t\t<tr><input type=\"hidden\" value=\"153-60-00064\">\r\n");
      out.write("\t\t\t<td width=100>대분류 상품 코드</td>\r\n");
      out.write("\t\t\t<td width=300>대분류 상품 이름</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t<tr class=\"lcategory\">\r\n");
      out.write("\t\t\t<td width=100 class=\"lcategorycode\">001</td>\r\n");
      out.write("\t\t\t<td width=300 class=\"lcategoryname\"><input type=\"text\" size=30 class=\"largename\" placeholder=\"ex)노트북,데스크탑,휴대폰 등..\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"lcategory\">\r\n");
      out.write("\t\t\t<td width=100 class=\"lcategorycode\">002</td>\r\n");
      out.write("\t\t\t<td width=300 class=\"lcategoryname\"><input type=\"text\" size=30 class=\"largename\" placeholder=\"ex)상의,하의,아우터 등..\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr class=\"lcategory\">\r\n");
      out.write("\t\t\t<td width=100 class=\"lcategorycode\">003</td>\r\n");
      out.write("\t\t\t<td width=300 class=\"lcategoryname\"><input type=\"text\" size=30 class=\"largename\" placeholder=\"ex)커피,차,에이드 등..\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"submit\" value=\"저장\">\r\n");
      out.write("\t<input type=\"reset\" value=\"취소\"> \r\n");
      out.write("</form>\r\n");
      out.write("<form id=\"frm1\" method=\"post\" action=\"categoryinsert\">\r\n");
      out.write("\t<table id=\"tbl1\" border=1></table>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"submit\" value=\"저장\">\r\n");
      out.write("\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(frm1).hide();\r\n");
      out.write("\r\n");
      out.write("//getList();\r\n");
      out.write("\r\n");
      out.write("function getList() {\r\n");
      out.write("\tvar addList = \"\";\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"categorylist.json\",\r\n");
      out.write("\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\tif($(data.NAME)!= null){\r\n");
      out.write("\t\t\t\taddList += \"<thead><td width=100>대분류</td><td width=100>중분류 상품 코드</td><td width=100>중분류 상품 이름</td></thead><tbody id='body'>\";\r\n");
      out.write("\t\t\t\t$(data).each(function() {\r\n");
      out.write("\t\t\t\t\taddList += \"<tr class='category' ><td width=100 class='lcategoryname' rowspan=4>\"+this.NAME.split(\"/\")[1]+\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<tr class='row' code='\"+this.CODE+\"' name='\"+this.NAME+\"'><td width=100 class='mcategorycode'>001</td>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<td width=100 class='mcategoryname' ><input type='text' size=30  class='midname' placeholder='ex)아메리카노,아이스라떼,카페모카 등..'></td></tr>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<tr class='row' code='\"+this.CODE+\"'name='\"+this.NAME+\"'><td width=100 class='mcategorycode'>002</td>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<td width=100 class='mcategoryname'><input type='text' size=30 class='midname' ></td></tr>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<tr class='row' code='\"+this.CODE+\"'name='\"+this.NAME+\"'><td width=100 class='mcategorycode'>003</td>\";\r\n");
      out.write("\t\t\t\t\taddList += \"<td width=100 class='mcategoryname'><input type='text' size=30  class='midname' ></td></tr>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\taddList +=\"</tbody>\";\r\n");
      out.write("\t\t\t\t$(\"#tbl1\").html(addList);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\t$(\"#btnadd\").click(function(){\r\n");
      out.write("\t\tif(!$(frm).is(\":hidden\")){\r\n");
      out.write("\t\t\tvar trCnt=$(\"#tbl tr\").length;\r\n");
      out.write("\t\t\tif(trCnt<10){\r\n");
      out.write("\t\t\t\tvar trCnt1 =\"00\"+trCnt;\r\n");
      out.write("\t\t\t}else if(trCnt<100 && trCnt>=10) {\r\n");
      out.write("\t\t\t\ttrCnt1=\"0\"+trCnt;\r\n");
      out.write("\t\t\t}else if(trCnt>=100) {\r\n");
      out.write("\t\t\t\ttrCnt1=trCnt;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\tstr+=\"<tr class='lcategory'>\";\r\n");
      out.write("\t\t\tstr+=\"<td class='lcategorycode'>\"+trCnt1+\"</td>\";\r\n");
      out.write("\t\t\tstr+=\"<td class='lcategoryname'><input type='text' class='largename' size=30></td>\";\r\n");
      out.write("\t\t\tstr+=\"</tr>\";\r\n");
      out.write("\t\t\t$(\"#tbl > tbody:last\").append(str);\r\n");
      out.write("\t\t}else if(!$(frm1).is(\":hidden\")){\r\n");
      out.write("\t\t\tvar trCnt=$(\"#tbl1 tbody .row\").length;\r\n");
      out.write("\t\t\talert(trCnt);\r\n");
      out.write("\t\t\tif(trCnt<10){\r\n");
      out.write("\t\t\t\tvar trCnt1 =\"00\"+trCnt;\r\n");
      out.write("\t\t\t}else if(trCnt<100 && trCnt>=10) {\r\n");
      out.write("\t\t\t\ttrCnt1=\"0\"+trCnt;\r\n");
      out.write("\t\t\t}else if(trCnt>=100) {\r\n");
      out.write("\t\t\t\ttrCnt1=trCnt;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\tstr+=\"<tr class='row'><td width=100 class='mcategorycode'>\"+trCnt1+\"</td>\";\r\n");
      out.write("\t\t\tstr+=\"<td width=100 class='mcategoryname'><input type='text' size=30 class='midname' ></td></tr>\";\r\n");
      out.write("\t\t\t$(\"#tbl1 > tbody:last\").append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btndel\").click(function(e){\r\n");
      out.write("\t\t$(\"#tbl > tbody:last > tr:last\").remove();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm).submit(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tif(!$(frm).is(\":hidden\")){\r\n");
      out.write("\t\t\t$(\"#tbl .lcategory\").each(function(){\r\n");
      out.write("\t\t\tvar strlcode=$(this).find(\".lcategorycode\").html();\r\n");
      out.write("\t\t\tvar lcode=\"153-60-00064/\"+strlcode+\"/000\";\r\n");
      out.write("\t\t\tvar strlname=$(this).find(\".lcategoryname\").find(\".largename\").val();\r\n");
      out.write("\t\t\tvar lname=\"골드스탁/\"+strlname+\"/empty\";\r\n");
      out.write("\t\t\tif(strlname!=\"\"){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\turl :\"categoryinsert\",\r\n");
      out.write("\t\t\t\tdata :{\"categorycode\": lcode, \"categoryname\":lname},\r\n");
      out.write("\t\t\t\tsuccess: function(){\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\talert(\"저장완료 되었습니다\");\r\n");
      out.write("\t\t$(frm).hide();\r\n");
      out.write("\t\t$(frm1).show();\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(frm1).submit(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tif(!$(frm1).is(\":hidden\")){\r\n");
      out.write("\t\t\t$(\"#tbl1 .row\").each(function() {\r\n");
      out.write("\t\t\t\tvar lcode=$(this).attr(\"code\");//153-60-00064/001\r\n");
      out.write("\t\t\t\tvar lname=$(this).attr(\"name\");//골드스탁/컴퓨터\r\n");
      out.write(" \t\t\t\tvar strmcode=$(this).find(\".mcategorycode\").html();//001\r\n");
      out.write(" \t\t\t\tvar mcode=lcode+\"/\"+strmcode;\r\n");
      out.write(" \t\t\t\tvar strmname=$(this).find(\".mcategoryname\").find(\".midname\").val();\r\n");
      out.write(" \t\t\t\tvar mname=lname+\"/\"+strmname;\r\n");
      out.write(" \t\t\t\talert(lname);\r\n");
      out.write("\t\t\t\tif(strmname!=\"\"){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"post\", \r\n");
      out.write("\t\t\t\t\t\turl :\"categoryinsert\",\r\n");
      out.write("\t\t\t\t\t\tdata :{\"categorycode\": mcode, \"categoryname\":mname},\r\n");
      out.write("\t\t\t\t\t\tsuccess: function(){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\talert(\"저장완료 되었습니다\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
